const data = [
  { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYs3xEQRQTuH1NT3Ueh9X9s8ruK224BAqbOZHTFzRiIZyAN7OWotl0Rif0hJx7sYyK9yk&usqp=CAU", id: 1, category: "Croissant", price: 12, stars: 4 },
  { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHkmKxGMmJhypohL9nRxJZFwsvaHTvxLquIx3ryTcOgiu4XUHFhkpryT08P5EkPDZ01hQ&usqp=CAU", id: 2, category: "Unknown", price: 7, stars: 3 },
  { image: "https://www.eatingwell.com/thmb/R_sQXK3H5d0Sbh9eWgHxENqMrsQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/EWL-SEO-62-Anti-Inflammatory-Energy-Balls-Hero-1x1-8656-e680c9a00655456c92fa2cc6110066ca.jpg", id: 3, category: "Custard pie", price: 15, stars: 5 },
  { image: "https://stordfkenticomedia.blob.core.windows.net/df-us/rms/media/recipesmedia/recipes/retail/x17/2009/apr/2018_sweet-sallty-snack-mix_5817_600x600.jpg?ext=.jpg", id: 4, category: "Donut", price: 10, stars: 4 },
  {image:"https://www.gourmetgiftbaskets.com/images/products/5636B/Happy-Birthday-Sweet-and-Savory-Deluxe_1000x1000.jpg" , id: 5, category: "Coffee", price: 8, stars: 4 },
  {image:"https://thefitfork.com/wp-content/uploads/2024/07/Crispy-Chocolate-Banana-Bites-squ-1000-b.jpg" , id: 6, category: "Cake", price: 20, stars: 5 },
  {image:"https://www.gourmetgiftbaskets.com/images/products/4103/Snack-Chocolate-Gift-Basket-Deluxe_1000x1000.jpg" , id: 7, category: "Cookie", price: 5, stars: 3 },
  {image:"https://m.media-amazon.com/images/I/81ShL6YNTSL._AC_UF1000,1000_QL80_.jpg" , id: 8, category: "Bread", price: 4, stars: 2 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3tiiwjs63_9a41xizOtS018lhB6W9R4Ws0Q&s" , id: 9, category: "Favorites", price: 25, stars: 5 },
  {image:"https://m.media-amazon.com/images/I/71LuDIRZYSL._AC_UF1000,1000_QL80_.jpg" , id: 10, category: "Most popular", price: 30, stars: 5 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-_Mg8PyMB0ai741nhIaJPowfwsULx2tzLgQ&s" , id: 11, category: "Croissant", price: 13, stars: 4 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSykfdLHsoh-hi-Jz42bWPcPGCAAnbL_xv8Dg&s" , id: 12, category: "Cupcake", price: 6, stars: 3 },
  {image:"https://i0.wp.com/eatmediterraneanfood.com/wp-content/uploads/2016/11/Roasted-Sweet-Potatoes-with-Sage-square.jpg?fit=1000%2C1000&ssl=1" , id: 13, category: "Custard pie", price: 18, stars: 4 },
  {image:"https://www.lundberg.com/cdn/shop/files/RiceCake_Reg_HoneyNut_Img_Transition_1000_5c5cc7a0-db53-41b0-954b-00b3db78ef00_1200x.jpg?v=1720063056" , id: 14, category: "Donut", price: 9, stars: 3 },
  {image:"https://m.media-amazon.com/images/I/81Js05PEukL._AC_UF1000,1000_QL80_.jpg" , id: 15, category: "Coffee", price: 7, stars: 4 },
  {image:"https://m.media-amazon.com/images/I/71ju24iuLmL._AC_UF1000,1000_QL80_.jpg" , id: 16, category: "Cake", price: 22, stars: 5 },
  {image:"https://www.mastermindtoys.com/cdn/shop/files/fashion-angels-stack-attack-sticker-stacking-system-fast-food-228374-960270_1200x.jpg?v=172893315" , id: 17, category: "Cookie", price: 6, stars: 3 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxRmYX4OqLGoOrbQXe2XFcDAbNphmu7dgkdQ&s" , id: 18, category: "Bread", price: 3, stars: 2 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-EYoQJFnnbUWSiGM5ieKDV4QLFhye_iFhEQ&s" , id: 19, category: "Favorites", price: 28, stars: 5 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0cFleHkr83XTp-0AALLRqiAOs7nZxme-OVQ&s" , id: 20, category: "Most popular", price: 35, stars: 5 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwsAkso1Z1vkgzop4N_Y9P_1WgCEwWqjoOfA&s" , id: 21, category: "Croissant", price: 11, stars: 4 },
  {image:"https://media.istockphoto.com/id/1407832840/photo/foods-enhancing-the-risk-of-cancer-junk-food.jpg?s=612x612&w=0&k=20&c=IBXz9XVfsZS-MM-AOW1kGel3WtgIDZpewFpNO2hGTGE=" , id: 22, category: "Cupcake", price: 7, stars: 3 },
  {image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLSq4t5f0vGuyRA10_cVq6EIW2psHZulHkWA&s" , id: 23, category: "Custard pie", price: 16, stars: 4 },
  {image:"" , id: 24, category: "Donut", price: 10, stars: 3 },
  {image:"" , id: 25, category: "Coffee", price: 9, stars: 4 },
  {image:"" , id: 26, category: "Cake", price: 21, stars: 5 },
  {image:"" , id: 27, category: "Cookie", price: 8, stars: 3 },
  {image:"" , id: 28, category: "Bread", price: 5, stars: 2 },
  {image:"" , id: 29, category: "Favorites", price: 27, stars: 5 },
  {image:"" , id: 30, category: "Most popular", price: 32, stars: 5 },
  {image:"" , id: 31, category: "Croissant", price: 14, stars: 4 },
  {image:"" , id: 32, category: "Cupcake", price: 8, stars: 3 },
  {image:"" , id: 33, category: "Custard pie", price: 19, stars: 5 },
  {image:"" , id: 34, category: "Donut", price: 11, stars: 3 },
  {image:"" , id: 35, category: "Coffee", price: 10, stars: 4 },
  {image:"" , id: 36, category: "Cake", price: 23, stars: 5 },
  {image:"" , id: 37, category: "Cookie", price: 7, stars: 3 },
  {image:"" , id: 38, category: "Bread", price: 6, stars: 2 },
  {image:"" , id: 39, category: "Favorites", price: 26, stars: 5 },
  {image:"" , id: 40, category: "Most popular", price: 31, stars: 5 },
  {image:"" , id: 41, category: "Croissant", price: 12, stars: 4 },
  {image:"" , id: 42, category: "Cupcake", price: 9, stars: 3 },
  {image:"" , id: 43, category: "Custard pie", price: 17, stars: 4 },
  {image:"" , id: 44, category: "Donut", price: 12, stars: 3 },
  {image:"" , id: 45, category: "Coffee", price: 11, stars: 4 },
  {image:"" , id: 46, category: "Cake", price: 24, stars: 5 },
  {image:"" , id: 47, category: "Cookie", price: 9, stars: 3 },
  {image:"" , id: 48, category: "Bread", price: 7, stars: 2 },
  {image:"" , id: 49, category: "Favorites", price: 29, stars: 5 },
  {image:"" , id: 50, category: "Most popular", price: 33, stars: 5 },
  {image:"" , id: 51, category: "Croissant", price: 15, stars: 4 },
  {image:"" , id: 52, category: "Cupcake", price: 10, stars: 3 },
  {image:"" , id: 53, category: "Custard pie", price: 20, stars: 5 },
  {image:"" , id: 54, category: "Donut", price: 13, stars: 3 },
  {image:"" , id: 55, category: "Coffee", price: 12, stars: 4 },
  {image:"" , id: 56, category: "Cake", price: 25, stars: 5 },
  {image:"" , id: 57, category: "Cookie", price: 10, stars: 3 },
  {image:"" , id: 58, category: "Bread", price: 8, stars: 2 },
  {image:"" , id: 59, category: "Favorites", price: 30, stars: 5 },
  {image:"" , id: 60, category: "Most popular", price: 34, stars: 5 },
];

export default data;
